server:
  port: 8761
security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
eureka:
  instance:
    hostname: localhost
  server:
    #enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.156:${server.port}/eureka
#jasypt:
#  encryptor:
#    password: xxx