server:
  port: 8759
security:
  user:
    name: admin
    password: ymadmin
  basic:
    enabled: true
eureka:
  instance:
    hostname: uat
  server:
    #enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
jasypt:
  encryptor:
    password: xxxxx