server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        context-path: /hpwxmobile  #  根路径
    port: 8002
spring:
  application:
    name: hp-wx-mobile
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.147.104:3306/wx?useUnicode=true&characterEncoding=UTF-8&?useSSL=false
    username: root
    password: Quanhe_2018
    
    
  #  微信接 token   
wx:
  token: 335333443