server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    context-path: /hpwxmobile  #  根路径
    port: 5001    # 8002 spring:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.147.104:3306/wx?useUnicode=true&characterEncoding=UTF-8&?useSSL=false
    username: root
    password: Quanhe_2018
  redis: 
    open: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password: hp1234
    timeout: 6000
    pool:
      max-active: 100
      max-wait: 3000
      max-idle: 10
      min-idle: 5
wx:
  appId:  wxa1348afe4982240b
  secret: wjpCUYrnVqtw2pVoippD3UzRglGd0DThjHZBbXIBhvH 
  token: wx1234
