spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.246:3306/wechat_520_activity?useUnicode=true&characterEncoding=UTF-8&?useSSL=false
    username: wct520
    password: 6cC_0347a1_aa10A32c11e
  redis: 
    open: false
    database: 0
    host: www.queriestech.com
    port: 6379
    password: hp123
    timeout: 6000
    pool:
      max-active: 100
      max-wait: 3000
      max-idle: 10
      min-idle: 5
wx:
  appId: wx0e938c00ca8232a9
  secret: 667f391fe45f6b97d3c206f83f3a3958 
  token: wx1234
