server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    context-path: /hpwxmobile  #  根路径
    port: 5001    # 8002 spring:
spring:
  jackson: 
        time-zone:  GMT+8
        date-format:  yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.147.104:3306/wx?useUnicode=true&characterEncoding=UTF-8&?useSSL=false
    username: root
    password: Quanhe_2018
  redis: 
    open: false
    database: 0
    host: 127.0.0.1
    port: 6379
    password: hp1234
    timeout: 6000
    pool:
      max-active: 100
      max-wait: 3000
      max-idle: 10
      min-idle: 5
logging:
    level:
        com.hp: DEBUG
    root: INFO
wx:
  appId: wx0e938c00ca8232a9
  secret: 667f391fe45f6b97d3c206f83f3a3958 
  token: wx1234

