spring:
    application:
       name: hp-wx-api
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.27.147.104:3306/wx?useUnicode=true&characterEncoding=UTF-8 
        username: root
        password: Quanhe_2018 
        dbcp2:
	      　　min-idle: 5         #数据库连接池的最小维持连接数
	      　　initial-size: 5     #初始化提供的连接数
	      　　max-total: 10          #最大的连接数
	      　　max-wait-millis: 500000        #等待连接获取的最大超时时间  
eureka:
  client:
    serviceUrl:
       defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}