# Tomcat
server:
    port: 8052
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    
    connection-timeout: 5000
spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        
        
        
auth:
   wechat:
      appId: xxxddd
      secret:dddddd
