server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 5000    # 8001
    connection-timeout: 5000
    context-path: /hpwxpc
spring:
    tomcat:
    application:
       name: hp-bg-api
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:  #数据源1
                url: jdbc:mysql://10.0.0.246:3306/wx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&?useSSL=false
                username: root
                password: Quanhe_2018
            second:  #数据源2
                 url: jdbc:mysql://120.27.147.104:3306/wx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8??useSSL=false
                 username: root                         
                 password: Quanhe_2018
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

                        
 # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】       
renren:
    jwt:
        # 加密秘钥
        secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
        # token有效时长，7天，单位秒
        expire: 604800
        header: token
imageurl: http://localhost:5000
imageuploadpath: /hpwxpc/hpwx/uploadImages/
